/* 🧠 THE TAGGING BRAIN */

const tagDictionary = {

    // --- BASE EXPRESSIONS ---
    "chuckle/chuckles/chuckled/chucking": ["#chuckle", "#expression", "#sound"],
    "smirk/smirks/smirked/smirking": ["#smirk", "#expression"],
    "beam/beams/beamed/beaming": ["#Beam", "#Radiant", "#Bright", "#expression"],
    "laugh/laughs/laughed/laughing": ["#laugh", "#expression", "#sound", "#action"],
    "grin/grins/grinned/grinning": ["#grin", "#Expression", "#action"],
    "smile/smiles/smiled/smiling": ["#smile", "#expression", "#emotion", "#manner"],
    "scowl/scowls/scowled/scowling": ["#scowl", "#expression", "#emotion", "#attitude", "#manner"],
    "frown/frowns/frowned/frowning": ["#frown", "#expression", "#emotion", "#attitude", "#manner"],
    "grimace/grimaces/grimaced/grimacing": ["#grimace", "#expression", "#action", "#emotion", "#manner"],
    "sneer/sneers/sneered/sneering": ["#sneer", "#expression", "#emotion", "#attitude", "#speech", "#manner"],
    "cry/cries/cried/crying/shed tears": ["#cry", "#expression", "#emotion", "#action", "#sound"],
    "hey": ["#hey"],
    "sample": ["#sample"],
    "SAMPLE TEXT": ["#TEXT"],
    "heynew": ["#heynew"],
    "new": ["#new"],

    // --- EXPRESSION - EXTENDED ---
    "wide eyes/wide eye/wide eyed": ["#shock", "#surprised"],
    "raise eyebrow/raises eyebrow/raised eyebrow/raising eyebrow/raise eyebrows/raises eyebrows/raised eyebrows/raising eyebrows/raise an eyebrow/raises an eyebrow/raised an eyebrow/raising an eyebrow/raise her eyebrow/raises her eyebrow/raised her eyebrow/raising her eyebrow/raise his eyebrow/raises his eyebrow/raised his eyebrow/raising his eyebrow/raise her eyebrows/raises her eyebrows/raised her eyebrows/raising her eyebrows/raise his eyebrows/raises his eyebrows/raised his eyebrows/raising his eyebrows/raise my eyebrow/raises my eyebrow/raised my eyebrow/raising my eyebrow/ raise my eyebrows/raises my eyebrows/raised my eyebrows/raising my eyebrows": ["#amused", "#knowing", "#expression"],
    "surprised": ["#surprised"],

    // --- EMOTIONS ---
    "weep/weeps/wept/weeping": ["#weep", "#emotion", "#expression", "#sound", "#action"],
    "uncaring": ["#uncaring", "#emotion"],
    "glare/glares/glared/glaring/glaringly": ["#glare", "#emotion", "#attitude", "#expression", "#action", "#sight"],

    // --- NEGATIVE SENSATIONS ---
    "ache/aches/ached/aching": ["#ache"],
    "swell/swells/swelled/swelling": ["#swell"],
    "sore/sores/soreness/sorely": ["#sore"],
    "pain/pains/ pained/ painful/ wince/wincing": ["#pain", "#sensation", "#negative sensation"],
    "agony/agonize/agonized/agonizing/in pain": ["#agony", "#tormented", "#sensation", "#negative sensation"],
    "sting/stings/stung/twinge/ twinges/twinging/ twinged": ["#sting", "#twinge"],
    "cramp/cramps/cramped/cramping": ["#cramp"],
    "burn/burns/burned/burning": ["#burn"],
    "pang/pang/pangs/panging/panged": ["#pang"],

    // --- SENSUAL / SPICY ---
    "Alluring/Appealing/Attractive/Charming/Captivating": ["#Alluring", "#Appealing", "#Attractive", "#Charming", "#Captivating"],
    "tempting/enticing/tantalizing/seductive": ["#tempting", "#enticing", "#tantalizing", "#seductive"],

    // --- NOUN: OBJECTS ---
    "Coffee/espresso/macchiato/Cappuccino/Latte/Mocha/caffeine": ["#coffe", "#latte", "#caffeine"],
    "coffeemaker": ["#coffeemaker"],
    "coffeepot": ["#coffeepot"],
    "coffeetime": ["#coffeetime"],
    "decaffeinated": ["#decaffeinated"],

    // --- VENUES ---
    "Plant/Plants": ["#Plant"],
    "Hospital/Hospitals": ["#Hospital"],
    "Clinic/Clinics": ["#Clinic"],
    "Library/Libraries": ["#Library"],
    "University/Universities": ["#University"],
    "Basement/Basements": ["#Basement"],
    "apartment/apartments": ["#apartment"],
    "office/offices": ["#office"],
    "school/schools": ["#school"],
    "room/rooms": ["#room"],
    "bridge/bridges": ["#bridge"],
    "Cabin/Cabins": ["#Cabin"],
    "Condo/Condos/Condominium/Condominiums": ["#Condo"],
    "Cottage/Cottages": ["#Cottage"],
    "Dorm/Dorms/Dormitory/Dormitories": ["#Dorm"],
    "House/Houses": ["#House"],
    "Mansion/Mansions": ["#Mansion"],
    "Bakery/Bakeries": ["#Bakery"],
    "Bar/Bars": ["#Bar"],
    "Mall/Malls/Shoppingmall": ["#Mall"],
    "Studio/studios": ["#Studio"],
    "Market/Markets": ["#Market"],
    "Supermarket/Supermarkets": ["#Supermarket"],
    "Restaurant/Restaurants/Diner/Diners/Eatery": ["#Restaurant", "#Diner"],
    "Shop/Shops": ["#Shop"],
    "Store/Stores": ["#Store"],
    "Airport/Airports": ["#Airport"],
    "Hotel/Hotels": ["#Hotel"],
    "Inn/Inns": ["#Inn"],
    "Motel/Motels": ["#Motel"],
    "Resort/Resorts": ["#Resort"],
    "Station/Stations": ["#Station"],
    "Bank/Banks": ["#Bank"],
    "Church/Churches": ["#Church"],
    "Gym/Gyms": ["#Gym"],
    "Museum/Museums": ["#Museum"],
    "Park/Parks": ["#Park"],
    "Bungalow/Bungalows": ["#Bungalow"],
    "Duplex/Duplexes": ["#Duplex"],
    "Farmhouse/Farmhouses": ["#Farmhouse"],
    "Loft/Lofts": ["#Loft"],
    "Penthouse/Penthouses": ["#Penthouse"],
    "Manor/Manors": ["#Manor"],
    "Trailer/Trailers": ["#Trailer"],
    "Villa/Villas": ["#Villa"],
    "Arena/Arenas": ["#Arena"],
    "Arcade/Arcades": ["#Arcade"],
    "Casino/Casinos": ["#Casino"],
    "Theater/Theaters": ["#Theater"],
    "Cinema/Movie Theater/Cinemas/Movie Theaters": ["#Cinema", "#Movie Theater"],
    "Club/Clubs": ["#Club"],
    "Gallery/Galleries": ["#Gallery"],
    "Playground/Playgrounds": ["#Playground"],
    "Pool/Pools": ["#Pool"],
    "Spa/Spas": ["#Spa"],
    "Stadium/Stadiums": ["#Stadium"],
    "Zoo/Zoos": ["#Zoo"],
    "Barn/Barns": ["#Barn"],
    "Factory/Factories": ["#Factory"],
    "Greenhouse/Greenhouses": ["#Greenhouse"],
    "Harbor/Harbors": ["#Harbor"],
    "Garage/Garages": ["#Garage"],
    "Laboratory/Lab/Laboratories/Labs": ["#Lab"],
    "Mill/Mills": ["#Mill"],
    "Port/Ports": ["#Port"],
    "Warehouse/Warehouses": ["#Warehouse"],
    "Workshop/Workshops": ["#Workshop"],
    "Home/Homes": ["#home"],
    "café/cafe/coffee shop/coffee place/Coffeehouse/Coffee lounge/Corner café/Lounge café/Cafes/cafés": ["#cafe", "#venue", "#coffeeshop"],

    // --- TIME ---
    "Second/Seconds": ["#Second"],
    "Minute/Minutes": ["#Minute"],
    "Hour/Hours": ["#Hour"],
    "Day/Days": ["#Day"],
    "Week/Weeks": ["#Week"],
    "Month/Months/couple of weeks": ["#Month"],
    "Year/Years": ["#Year"],
    "Decade/Decades": ["#Decade"],
    "Century/Centuries": ["#Century"],
    "Millennium": ["#Millennium"],
    "lifetime": ["#lifetime"],
    "Afternoon/Midday/Noon": ["#Afternoon", "#daytime", "#midday"],
    "Morning/Mornings": ["#morning", "#daytime"],
    "Evening/Evenings/Night/Nights": ["#evening"],
    "Midnight": ["#Midnight"],
    "Monday/Mondays": ["#Monday"],
    "Tuesday/Tuesdays": ["#Tuesday"],
    "Wednesday/Wednesdays": ["#Wednesday"],
    "Thursday/Thursdays": ["#Thursday"],
    "Friday/Fridays": ["#Friday"],
    "Saturday/Saturdays": ["#Saturday"],
    "Sunday,Sundays": ["#Sunday"],
    "weekend/weekends": ["#weekend"],
    "weekday/weekdays": ["#weekday"],
    "January": ["#January"],
    "February": ["#February"],
    "March": ["#March"],
    "April": ["#April"],
    "May": ["#May"],
    "June": ["#June"],
    "July": ["#July"],
    "August": ["#August"],
    "September": ["#September"],
    "October": ["#October"],
    "November": ["#November"],
    "December": ["#December"],
    "winter": ["#winter", "#season"],
    "spring": ["#spring", "#season"],
    "summer": ["#summer", "#season"],
    "autumn": ["#autumn", "#season"],
    "first/1st": ["#first"],

    // --- ANATOMY ---
    "hair/hairs/strand/strands": ["#hair"],
    "head": ["#head"],
    "forehead/foreheads/front of the head": ["#forehead"],
    "eye/eyes": ["#eyes"],
    "eyebrow/eyebrows/brow/brows": ["#eyebrow"],
    "eyelash/eyelashes/lashes": ["#eyelash"],
    "eyelid/eyelids": ["#eyelid"],
    "cheek/cheeks": ["#cheek"],
    "nose/noses/nostril/nostrils": ["#nose"],
    "ear/ears/earlobe/earlobes/lobe": ["#ear"],
    "lip/lips": ["#lips"],
    "mouth/mouthed": ["#mouth"],
    "temple/temples": ["#temples"],
    "face/faces": ["#face"],
    "tongue/tongues": ["#tongue"],
    "throat/throats": ["#throat"],
    "neck/necks": ["#neck"],
    "stubble/stubbles": ["#stubble"],
    "moustache": ["#moustache"],
    "beard/beards/bearded/facial hair/whisker/whiskers/goatee": ["#beard", "#facialhair"],
    "chin": ["#chin"],
    "dimple/dimples": ["#dimple"],
    "birthmark": ["#birthmark"],
    "mole/moles": ["#mole"],
    "scar/scars": ["#scar"],
    "wound/wounds/wounded": ["#wound"],
    "freckle/freckles/blemish": ["#freckles"],
    "skin/skins": ["#skin"],
    "shoulder/shoulders": ["#shoulder"],
    "chest/chests/bust": ["#chest"],
    "jaw/jaws/jawbone": ["#jaw"],
    "pelvis/V-line/pelvic": ["#pelvis"],
    "thigh/thighs": ["#thighs"],
    "leg/legs": ["#leg"],
    "limb/limbs": ["#limb"],
    "butt/buttock/buttocks/glute/ass": ["#ass", "#butt"],
    "calf/calves": ["#calf"],
    "knee/knees": ["#knee"],
    "ankle/ankles": ["#ankle"],
    "feet/foot": ["#feet"],
    "toe/toes": ["#toes"],
    "heel/heels": ["#heel"],
    "arm/arms/bicep/biceps/tricep/triceps": ["#arm"],
    "hand/hands": ["#hand"],
    "wrist/wrists": ["#wrist"],
    "palm/palms": ["#palm"],
    "finger/fingers": ["#finger"],
    "thumb/thumbs": ["#thumb"],
    "nail/nails": ["#nail"],
    "elbow/elbows": ["#elbow"],
    "sole/soles": ["#sole"],
    "navel": ["#navel"],
    "spine/spines/backbone": ["#spine"],
    "muscle/muscles": ["#muscle"],
    "nipple/nipples/tit/tits": ["#nipples", "#nsfw"],
    "breast/breasts/bosom/bosoms/boob/boobs/globes": ["#breast", "#nsfw"],
    "vagina/cunt/pussy/muff/folds": ["#vagina", "#nsfw"],
    "penis/shaft/junk/dick/cock": ["#penis", "#nsfw"],
    "clitoris/clit": ["#clit", "#nsfw"],
    "cervix": ["#cervix"],
    "anus/anal/rectum": ["#anus"],
    "Prostate": ["#Prostate"],
    "erect/erection/erected": ["#erection"],
    "balls/testes/testicles/scrotum": ["#balls"],
    "foreskin": ["#foreskin"],
    "vein/veins": ["#vein"],
    "kidney/kidneys": ["#kidney"],
    "bladder": ["#bladder"],
    "heart/hearts": ["#heart"],
    "lung/lungs": ["#lungs"],
    "stomach/stomachs/tummy/belly": ["#stomach"],
    "abs/abdominal/oblique/obliques/abdomen": ["#abs"],
    "blood/bloods/red liquid": ["#blood"],
    "gallbladder": ["#gallbladder"],
    "liver/livers": ["#liver"],
    "bone/bones": ["#bone"],
    "cartilage": ["#cartilage"],
    "Torso": ["#Torso"],
    "nape/back of the neck": ["#nape"],
    "collarbone/clavicle": ["#collarbone"],
    "rib/ribs/ribcage": ["#ribs"],
    "breastbone": ["#breastbone"],
    "waist/waists": ["#waist"],
    "hip/hips": ["#hips"],
    "knuckle/knuckles": ["#knuckle"],
    "shin": ["#shin"],
    "brain/brains": ["#brain"],
    "Intestine/Intestines": ["#Intestine"],
    "Spleen": ["#Spleen"],
    "Esophagus": ["#Esophagus"],
    "Pancreas": ["#Pancreas"],
    "Joint/Joints": ["#Joints"],
    "Groin": ["#Groin"],
    "Scalp": ["#Scalp"],
    "body/bodies": ["#body"],
    "Skull": ["#Skull"],
    "Colon": ["#Colon"],
    "Hamstring": ["#Hamstring"],
    "Diaphragm": ["#Diaphragm"],
    "Vascular": ["#Vascular"],
    "Artery/Arteries": ["#Artery"],
    "Femur": ["#Femur"],
    "Cell/cells": ["#Cell"],
    "Organ/Organs": ["#Organ"],
    "eyesight": ["#eyesight"],

    // --- NSFW ---
    "fetish/fetishes": ["#fetish"],
    "Hormone/hormones/hormonal": ["#Hormone"],
    "Hymen": ["#Hymen"],
    "orgasm/orgasms/orgasmed/orgasming": ["#orgasm", "#nsfw"],
    "fingering": ["#fingering", "#nsfw"],
    "spooning": ["#spooning"],
    "69": ["#69"],
    "sex/sexting/intercourse": ["#sex", "#nsfw"],
    "foreplay/foreplays": ["#foreplay", "#nsfw"],
    "kink/kinks": ["#kink"],
    "condom/protection/pills/condoms/protections/pill": ["#protection"],
    "dildo/dildos/adult toys/sex toys/Anal Beads/Anal Plug/Anal Toys/Vibrator/Butt Plug/Clit Pump/Cock Rings/cock cage/Fleshlight/Nipple Clamps/Sex Dolls/Strap-On/Training Beads/Vibrating Plugs": ["#sextoys", "#nsfw"],
    "masturbate/masturbation/masturbates/masturbating/masturbated": ["#masturbate", "#nsfw"],
    "horny": ["#horny"],
    "aroused/arousal/sexual pleasure/sexual pleasures": ["#aroused", "#nsfw"],
    "penetrate/penetrates/penetration/penetrating/penetrated/piston/pistoning": ["#penetrate"],
    "Hickey/Hickies": ["#Hickey"],
    "lube/lubrication/lubricant/lubricate/lubes/lubrications/lubricants/lubricates/lubricating/lubricated": ["#lube"],
    "Incest/Incests": ["#Incest"],
    "cuckhold/cuckholds": ["#cuckhold", "#nsfw"],
    "cuckquean/cuckqueans": ["#cuckquean", "#nsfw"],
    "semen": ["#semen"],
    "blowjob/blowjobs": ["#blowjob", "#nsfw"],
    "handjob/handjobs": ["#handjob", "#nsfw"],
    "cum/cumming/cummed/cums": ["#cum", "#nsfw"],
    "ejaculate/ejaculates/ejaculation/ejaculated/ejaculating": ["#ejaculate"],
    "missionary": ["#missionary"],

    // --- BIOLOGY TERMS ---
    "Estrogen/Estrogens": ["#Estrogen"],
    "Testosterone/Testosterones": ["#Testosterone"],
    "headache/ headaches": ["#headache"],
    "Ovulation/ovulated/ovulating": ["#ovulation"],
    "menstruation/menstruate/menstruating/menstruated/menstruates": ["#Menstruation"],
    "Menopause/Menopausal/Menopausing/Menopaused/Menopauses": ["#Menopause"],
    "migraine": ["#migraine"],
    "biolife": ["#biolife"],
    "stomachache": ["#stomachache"],
    "toothache": ["#toothache"],
    "backache": ["#backache"],

    // --- AUDITORY ---
    "growl/growls/growled/growling": ["#growl", "#sound", "#expression", "#attitude", "#action"],
    "snarl/snarls/snarled/snarling": ["#snarl", "#sound", "#expression", "#attitude", "#action"],
    "hiss/hisses/hissed/hissing": ["#hiss", "#sound", "#action", "#expression", "#speech", "#manner"],
    "whisper/whispers/whispered/whispering": ["#whisper", "#sound", "#speech", "#action", "#manner"],
    "murmur/murmurs/murmured/murmuring": ["#murmur", "#sound", "#speech", "#action", "#manner"],
    "mumble/mumbles/mumbled/mumbling": ["#mumble", "#speech", "#sound", "#manner", "#action"],
    "slur/slurs/slurred/slurring": ["#slur", "#speech", "#sound", "#attitude", "#expression", "#process"],
    "rumble/rumbles/rumbled/rumbling": ["#rumble", "#sound", "#movement", "#process"],
    "reverberate/reverberates/reverberated/reverberating": ["#reverberate", "#sound", "#movement", "#process"],
    "grumble/grumbles/grumbled/grumbling": ["#grumble", "#speech", "#sound", "#attitude", "#expression"],
    "moan/moans/moaned/moaning": ["#moan", "#sound", "#expression", "#emotion", "#sensation", "#speech"],
    "groan/groans/groaned/groaning": ["#groan", "#sound", "#expression", "#emotion", "#speech"],
    "scoff/scoffs/scoffed/scoffing": ["#scoff", "#speech", "#attitude", "#manner", "#expression"],
    "sigh/sighs/sighed/sighing": ["#sigh", "#sound", "#expression", "#emotion", "#action"],
    "gasp/gasps/gasped/gasping": ["#gasp", "#sound", "#action", "#expression", "#sensation"],
    "wail/wails/wailed/wailing": ["#wail", "#sound", "#expression", "#emotion", "#speech"],
    "roar/roars/roared/roaring": ["#roar", "#sound", "#action", "#speech", "#expression"],
    "bellow/bellows/bellowed/bellowing": ["#bellow", "#sound", "#speech", "#action", "#expression"],
    "howl/howls/howled/howling": ["#howl", "#sound", "#emotion", "#expression", "#speech"],
    "yell/yells/yelled/yelling": ["#yell", "#speech", "#sound", "#expression", "#action"],
    "shout/shouts/shouted/shouting": ["#shout", "#speech", "#sound", "#expression", "#action"],
    "scream/screams/screamed/screaming": ["#scream", "#sound", "#expression", "#emotion", "#speech", "#action"],
    "clamor/clamors/clamored/clamoring": ["#clamor", "#sound", "#action", "#speech", "#process"],
    "sob/sobs/sobbed/sobbing": ["#sob", "#sound", "#expression", "#emotion", "#movement", "#action"],
    "bawl/bawls/bawled/bawling": ["#bawl", "#sound", "#action", "#emotion", "#expression"],
    "wheeze/wheezes/wheezed/wheezing/labored breathing": ["#wheeze", "#sound", "#sensation", "#expression", "#process", "#speech"],
    "whistle/whistles/whistled/whistling": ["#whistle", "#sound", "#action", "#speech"],
    "rasp/rasps/rasped/rasping": ["#rasp", "#sound", "#sensation", "#action", "#manner"],
    "swear/swears/swore/sworn/swearing": ["#swear", "#speech", "#belief", "#communication", "#responsibility", "#attitude"],

    // --- BODY LANGUAGE ---
    "puff/puffs/puffed/puffing": ["#puff", "#action", "#movement", "#sound", "#sensation"],
    "inhale/inhales/inhaled/inhaling/breathe in": ["#inhale", "#action", "#process", "#movement", "#sensation"],
    "exhale/exhales/exhaled/exhaling/breath out": ["#exhale", "#action", "#movement", "#process", "#sound", "#sensation"],
    "blow/blows/blew/blowing": ["#blow", "#action", "#movement", "#sound", "#process"],
    "waft/wafts/wafted/wafting": ["#waft", "#movement", "#action", "#process", "#sensation"],
    "gust/gusts/gusted/gusting": ["#gust", "#movement", "#action", "#sound", "#process"],
    "choke/chokes/choked/choking": ["#choke", "#action", "#sensation", "#process"],
    "pant/pants/panted/panting/breathe heavily": ["#pant", "#action", "#sound", "#sensation", "#process"],
    "heave/heaves/heaved/heaving": ["#heave", "#action", "#movement", "#process"],
    "thrust/thrusts/thrust/thrusting": ["#thrust", "#action", "#movement", "#process"],
    "grind/grinds/grinded/grinding": ["#grind", "#action", "#process", "#sound", "#sensation"],
    "push/pushes/pushed/pushing": ["#push", "#action", "#movement", "#process", "#sensation"],
    "shove/shoves/shoved/shoving": ["#shove", "#action", "#movement", "#process"],
    "move/moves/moved/moving": ["#move", "#action", "#movement", "#process"],
    "press/presses/pressed/pressing/bear down": ["#press", "#action", "#movement", "#sensation", "#process"],
    "shift/shifts/shifted/shifting": ["#shift", "#action", "#movement", "#process"],
    "advance/advances/advanced/advancing": ["#advance", "#movement", "#action", "#process"],
    "change/changes/changed/changing": ["#change", "#action", "#process", "#movement"],
    "switch/switches/switched/switching": ["#switch", "#action", "#process", "#movement", "#tool"],
    "transform/transforms/transformed/transforming": ["#transform", "#action", "#process"],
    "alter/alters/altered/altering": ["#alter", "#action", "#process"],
    "convert/converts/converted/converting": ["#convert", "#action", "#process", "#movement"],
    "modify/modifies/modified/modifying": ["#modify", "#action", "#process"],
    "adapt/adapts/adapted/adapting": ["#adjust", "#process", "#action", "#attitude"],
    "correct/corrects/corrected/correcting": ["#correct", "#action", "#process", "#manner"],
    "fix/fixes/fixed/fixing": ["#fix", "#action", "#process", "#tool", "#object"],
    "amend/amends/amended/amending": ["#amend", "#action", "#process", "#speech"],
    "mend/mends/mended/mending": ["#mend", "#action", "#process", "#object"],
    "repair/repairs/repaired/repairing": ["#repair", "#action", "#process", "#object", "#tool"],
    "rectify/rectifies/rectified/rectifying": ["#rectify", "#action", "#process"],
    "restore/restores/restored/restoring": ["#restore", "#action", "#process", "#object"],
    "renovate/renovates/renovated/renovating": ["#renovate", "#action", "#process", "#object"],
    "renew": ["#renew", "#action", "#process"],
    "rebuild/rebuilds/rebuilt/rebuilding": ["#rebuild", "#action", "#process", "#object"],
    "revise/revises/revised/revising/re-examine": ["#revise", "#action", "#process", "#speech"],
    "review/reviews/reviewed/reviewing": ["#review", "#action", "#process", "#speech"],
    "edit/edits/edited/editing": ["#edit", "#action", "#process", "#speech", "#tool"],
    "revive/revives/revived/reviving": ["#revive", "#action", "#process", "#movement", "#emotion"],
    "reinstate/reinstates/reinstated/reinstating": ["#reinstate", "#action", "#process", "#role"],
    "refurbish/refurbishes/refurbished/refurbishing": ["#refurbish", "#action", "#process", "#object"],
    "extend/extends/extended/extending": ["#extend", "#action", "#process", "#movement", "#object"],
    "refresh/refreshes/refreshed/refreshing": ["#refresh", "#action", "#process", "#sensation", "#emotion"],
    "replace/replaces/replaced/replacing": ["#replace", "#action", "#process", "#object"],
    "revitalize/revitalizes/revitalized/revitalizing/reenergize/reenergized": ["#revitalize", "#action", "#process", "#sensation", "#emotion"],
    "walk/walks/walked/walking": ["#action", "#movement", "#manner", "#process"],
    "look/looks/looked/looking": ["#look", "#action", "#sight", "#vision", "#observation", "#attention"],
    "stare/stares/stared/staring": ["#stare", "#action", "#attitude", "#sight", "#vision", "#attention"],
    "view/views/viewed/viewing": ["#view", "#action", "#sight", "#perspective", "#observation", "#sensation"],
    "observe/observes/observed/observing": ["#observe", "#action", "#observation", "#attention", "#mental process", "#review"],
    "see/sees/saw/seen/seeing": ["#see", "#action", "#sight", "#sensation", "#cognition", "#mental process"],
    "glance/glances/glanced/glancing/quick look": ["#glance", "#action", "#movement", "#sight", "#attention", "#process"],
    "gaze/gazes/gazed/gazing": ["#gaze", "#action", "#attitude", "#attention", "#sight", "#mental process"],
    "peer/peers/peered/peering": ["#peer", "#action", "#attention", "#inquiry", "#examination", "#sight"],
    "fixate Branch: fixate/fixates/fixated/fixating": ["#fixate", "#action", "#attention", "#mental process", "#control", "#thought"],
    "glimpse/glimpses/glimpsed/glimpsing": ["#glimpse", "#sensation", "#action", "#sight", "#vision", "#observation"],
    "behold/beholds/beheld/beholding": ["#behold", "#action", "#sensation", "#sight", "#observation", "#mental process"],
    "scrutinize/scrutinizes/scrutinized/scrutinizing": ["#scrutinize", "#action", "#inquiry", "#examination", "#review", "#attention"],
    "watch/watches/watched/watching": ["#watch", "#action", "#observation", "#attention", "#surveillance", "#control"],
    "monitor/monitors/monitored/monitoring": ["#monitor", "#action", "#oversight", "#control", "#surveillance", "#verification"],
    "spot/spots/spotted/spotting": ["#spot", "#action", "#sight", "#observation", "#detection", "#boundary"],
    "focus/focuses/focused/focusing": ["#focus", "#action", "#attention", "#mental process", "#control", "#thought"],
    "catch/catches/caught/catching": ["#catch", "#action", "#movement", "#process", "#control", "#sensation"],
    "inspect/inspects/inspected/inspecting": ["#inspect", "#action", "#examination", "#review", "#oversight", "#verification"],
    "track/tracks/tracked/tracking": ["#track", "#action", "#movement", "#surveillance", "#process", "#control"],
    "check/checks/checked/checking": ["#check", "#action", "#verification", "#control", "#examination", "#review"],
    "detect/detects/detected/detecting": ["#detect", "#action", "#sensation", "#observation", "#vision", "#process"],
    "locate/locates/located/locating": ["#locate", "#action", "#process", "#boundary", "#observation", "#control"],
    "capture/captures/captured/capturing": ["#capture", "#action", "#control", "#movement", "#boundary", "#process"],
    "apprehend/apprehends/apprehended/apprehending": ["#apprehend", "#action", "#control", "#cognition", "#responsibility", "#movement"],
    "trap/traps/trapped/trapping": ["#trap", "#action", "#control", "#boundary", "#tool", "#method"],
    "dissect/dissects/dissected/dissecting": ["#dissect", "#action", "#examination", "#inquiry", "#study", "#process"],
    "investigate/investigates/investigated/investigating": ["#investigate", "#action", "#process", "#inquiry", "#examination", "#study", "#surveillance"],
    "research/researches/researched/researching": ["#research", "#action", "#process", "#study", "#inquiry", "#data", "#mental process"],
    "examine/examines/examined/examining": ["#examine", "#action", "#observation", "#oversight", "#review", "#data"],
    "seek/seeks/sought/seeking": ["#seek", "#action", "#inquiry", "#movement", "#process", "#attention"],
    "follow/follows/followed/following": ["#follow", "#action", "#movement", "#surveillance", "#process", "#attention"],
    "trace/traces/traced/tracing": ["#trace", "#action", "#inquiry", "#verification", "#history", "#surveillance"],
    "pursue/pursues/pursued/pursuing": ["#pursue", "#action", "#movement", "#process", "#attention", "#determination"],
    "trail/trails/trailed/trailing": ["#action", "#movement", "#surveillance", "#observation", "#process"],
    "care/cares/cared/caring/careful/carefully": ["#care", "#gesture"],
    "reconstruct/reconstructs/reconstructed/reconstructing": ["#reconstruct", "#action", "#process", "#object"],
    "sight/sights/sighted/sighting": ["#sight"],

    // --- COGNITION ---
    "perceive/perceives/perceived/perceiving": ["#perceive", "#cognition", "#mental process", "#sensation", "#thought", "#belief"],
    "notice/notices/noticed/noticing": ["#notice", "#cognition", "#mental process", "#observation", "#attention", "#thought"],
    "discern/discerns/discerned/discerning": ["#discern", "#cognition", "#mental process", "#thought", "#inquiry", "#examination"],
    "regard/regards/regarded/regarding": ["#regard", "#cognition", "#attitude", "#thought", "#belief", "#mental process", "#attention"],
    "concentrate/concentrates/concentrated/concentrating": ["#concentrate", "#cognition", "#mental process", "#thought", "#action", "#attention"],
    "recognize/recognizes/recognized/recognizing": ["#recognize", "#cognition", "#mental process", "#thought", "#belief", "#examination"],
    "analyze/analyzes/analyzed/analyzing": ["#analyze", "#cognition", "#process", "#examination", "#inquiry", "#study", "#mental process"],
    "study/studies/studied/studying": ["#study", "#cognition", "#process", "#mental process", "#inquiry", "#examination"],
    "inquire/inquires/inquired/inquiring": ["#cognition", "#speech", "#inquiry", "#communication", "#examination", "#process"],
    "testify/testifies/testified/testifying": ["#cognition", "#role", "#speech", "#communication", "#document", "#history"],
    "distinguish/distinguishes/distinguished/distinguishing": ["#distinguish", "#cognition", "#mental process", "#thought", "#boundary", "#examination"],
    "grasp/grasps/grasped/grasping": ["#grasp", "#cognition", "#sensation", "#mental process", "#action", "#process"],
    "deliberate/deliberates/deliberated/deliberating": ["#deliberate", "#mental process", "#thought", "#examination", "#process", "#cognition"],
    "ponder/ponders/pondered/pondering": ["#ponder", "#mental process", "#thought", "#inquiry", "#cognition", "#attention"],
    "identify/identifies/identified/identifying": ["#identify", "#cognition", "#verification", "#mental process", "#observation", "#data"],
    "learn/learns/learned/learning": ["#learn", "#process", "#cognition", "#mental process", "#study", "#history"],
    "query/queries/queried/querying": ["#query", "#cognition", "#speech", "#inquiry", "#communication", "#data", "#text"],
    "attest/attests/attested/attesting": ["#attest", "#cognition", "#speech", "#verification", "#communication", "#history", "#document"],
    "declare/declares/declared/declaring": ["#declare", "#cognition", "#speech", "#communication", "#status", "#belief"],
    "state/states/stated/stating": ["#state", "#cognition", "#speech", "#communication", "#data", "#text"],
    "classify/classifies/classified/classifying": ["#classify", "#cognition", "#mental process", "#boundary", "#data", "#organization", "#thought"],
    "discriminate/discriminates/discriminated/discriminating": ["#discriminate", "#mental process", "#boundary", "#cognition", "#thought", "#attitude"],
    "comprehend/comprehends/comprehended/comprehending": ["#comprehend", "#cognition", "#mental process", "#thought", "#belief", "#study"],
    "unbelievable": ["#unbelievable", "#cognition"],

    // --- ROLES ---
    "witness/witnesses/witnessed/witnessing": ["#witness", "#role", "#action", "#observation", "#history", "#document"],
    "supervise/supervises/supervised/supervising": ["#supervise", "#role", "#oversight", "#management", "#control", "#responsibility"],
    "caretaker/caregiver/caregivers": ["#caretaker", "#caregiver", "#role"],
    "benefactor/benefactress/benefactors/benefactresses": ["#benefactor", "#benefactress", "#role"],
    "believer/believers": ["#believer", "#role"],
    "distractor/distractors": ["#distractor", "#role"],

    // --- TERMINOLOGIES ---
    "act/acts/acted/acting/action/actions/active/actively": ["#act"],
    "beauty/beauties/beautiful/beautifully/beautify/beautified/beautifying/beautification": ["#beauty", "#beautiful"],
    "benefit/benefits/benefited/benefiting/beneficial/beneficially/beneficiaries": ["#benefit"],
    "clear/clears/cleared/clearing/clearly/clarity/clearance/clearness": ["#clear"],
    "unclear": ["#unclear"],
    "believe/believes/believed/believing/belief/beliefs/believable": ["#believe"],
    "consider/considers/considered/considering/consideration/considerations/considerate/considerately/considerable/considerably/reconsider/reconsideration": ["#consider"],
    "craze/crazes/crazed/crazing/crazy/crazily/craziness": ["#craze"],
    "create/creates/created/creating/creation/creations/creator/creators/creative/creatively/creativity/recreate/recreation": ["#create"],
    "decide/decides/decided/deciding/decision/decisions/decisive/decisively": ["#decide"],
    "undecided": ["#undecided"],
    "indecisive": ["#indecisive"],
    "delight/delights/delighted/delighting/delightful/delightfully": ["#delight"],
    "differ/differs/differed/differing/difference/differences/different/differently/differential/differentiate/differentiation": ["#differ"],
    "indifferent": ["#indifferent"],
    "indifference": ["#indifference"],
    "distract/distracts/distracted/distracting": ["#distract"],
    "distraction/distractions": ["#distraction"],
    "undistracted": ["#undistracted"],
    "njoy/enjoys/enjoyed/enjoying/enjoyment/enjoyable/unenjoyable": ["#enjoy"],
    "excel/excels/excelled/excelling/excellence/excellent/excellently": ["#excel"],
    "free/frees/freed/freeing/freely/freedom/freedoms/freer/freest": ["#free"],
    "hate/hates/hated/hating/hatred/hateful/hatefully/hater/haters": ["#hate"],
    "hope/hopes/hoped/hoping/hopeful/hopefully/hopeless/hopelessly": ["#hope"],
    "impress/impresses/impressed/impressing/impression/impressions/impressive/impressively/unimpressed": ["#impress"],
    "awe/awes/awed/awing/awful/awfully/awesome/awesomely": ["#awe"],
    "influence/influences/influenced/influencing/influential/uninfluenced/influencer/influencers": ["#influence"],
    "include/includes/included/including/inclusion/inclusive/inclusively/non-inclusive/preclude/exclusion": ["#include", "#inclusion"],
    "hum/hums/hummed/humming/hummer/hummingbird/hush": ["#hum"],
    "soft/softer/softest/softly/softness/soften/softens/softened/softening": ["#soft"],
    "afterlife": ["#afterlife"],
    "alive": ["#alive"],
    "lifelong": ["#lifelong"],
    "living": ["#living"],
    "livelihood": ["#livelihood"],
    "lifelike": ["#lifelike"],
    "lifeless": ["#lifeless"],
    "lively": ["#lively"],
    "life/lives": ["#life"],
    "discomfort/discomforts/discomforting/discomfortingly/ discomforted": ["#discomfort"],
    "uncomforted/uncomfortable/uncomfortably/uncomfortableness": ["#uncomfortable"],
    "comfort/comforts/comforted/comforting/comfortable/comfortably": ["#comfort"],
    "indicate/indicates/indicated/indicating/indication/indications/indicative": ["#indicate"],
    "indicator/indicators": ["#indicator"],
    "insult/insults/insulted/insulting/insultingly": ["#insult"],
    "unintentional/unintentionally": ["#unintentional"],
    "intentional/intentionally": ["#intentional"],
    "intention/intentions": ["#intention"],
    "intend/intends/intended/intending/intent/intents": ["#intend"],
    "disinterest/disinterested": ["#disinterest"],
    "uninterested": ["#uninterested"],
    "uninteresting": ["#uninteresting"],
    "interesting/interestingly": ["#interesting"],
    "interest/interests/interested": ["#interest"],
    "madman": ["#madman"],
    "madwoman": ["#madwoman"],
    "madness": ["#madness"],
    "mad/mads/madder/maddest/madly/madden/maddening": ["#mad"],
    "absent/absents/absented/absenting/absently/absence/absences/absentee/absenteeism": ["#Absent"],
    "mess/messes/messed/messing/messy/messily/messiness/mess-up": ["#mess"],
    "foresight": ["#foresight"],
    "hindsight": ["#hindsight"],
    "insight/insights": ["#insight"],
    "unsightly": ["#unsightly"],
    "sightless": ["#sightless"],
    "meditator": ["#meditator"],
    "meditate/meditates/meditated/meditating/meditation/meditations/meditative/meditatively": ["#meditate"],
    "careless/carelessly": ["#careless"],
    "unsurprising/unsurprisingly": ["#unsurprising"],
    "surprising/surprisingly": ["#surprising"],
    "surprise/surprises": ["#surprise"],
    "DONOTDELETETHIS": ["#DONOTDELETETHIS"]
};

/* --- ⚙️ THE ENGINE (Precision & Variations Support) --- */
function generateSmartTags(text) {
    if (!text) return "";
    let suggestedTags = new Set(); 
    for (const [key, tags] of Object.entries(tagDictionary)) {
        const variations = key.split('/');
        const matchFound = variations.some(trigger => {
            const cleanTrigger = trigger.trim();
            if (!cleanTrigger) return false;
            const regex = new RegExp(`\\b${cleanTrigger}\\b`, 'i');
            return regex.test(text);
        });
        if (matchFound) {
            tags.forEach(t => suggestedTags.add(t));
        }
    }
    return Array.from(suggestedTags).join(" ");
}
console.log("🧠 Brain Module Loaded (Precision Mode).");
